import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "react-bootstrap/Container";
import { ThemeProvider } from "@mui/material";
import { CategoryProvider } from "@/context/CategoryContext";
import { CartProvider } from "@/context/CartContext";
import theme from "@/styles/themes";
import Header from "@/components/layout/Header";
import AppBarApp from "@/components/layout/AppBar";
import { SearchProvider } from "@/context/SearchContext";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Soflex App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ background: "white" }}>
        <ThemeProvider theme={theme}>
          <CategoryProvider>
            <CartProvider>
              <SearchProvider>
                <AppBarApp />
                <Container className="d-flex justify-content-center">
                  {children}
                </Container>
              </SearchProvider>
            </CartProvider>
          </CategoryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
